"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables first
# load_dotenv(encoding='utf-8') # Explicit encoding
# If that fails, try generic load or just rely on system envs in prod
try:
    load_dotenv(encoding='utf-8')
except Exception:
    load_dotenv() # Fallback to default

# Testing Mode (Overridden in conftest.py)
import sys
IS_TESTING = (
    'test' in sys.argv or  # Django test command
    'pytest' in sys.modules or  # pytest runner
    any('pytest' in arg for arg in sys.argv) or  # pytest in command line
    os.environ.get('TESTING', '').lower() in ('true', '1', 'yes')  # Explicit env var
)

# =============================================================================
# Sentry 모니터링 설정 (에러 추적)
# https://sentry.io 에서 프로젝트 생성 후 DSN 발급
# =============================================================================
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
            ),
            LoggingIntegration(
                level=None,  # Capture all logs
                event_level="ERROR",  # Send ERROR+ as events
            ),
        ],
        # 환경 구분
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'development'),
        
        # 성능 모니터링 (샘플링 비율)
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        
        # 프로파일링 (성능 병목 분석)
        profiles_sample_rate=float(os.environ.get('SENTRY_PROFILES_SAMPLE_RATE', '0.1')),
        
        # PII(개인정보) 전송 여부 - False로 유지 권장
        send_default_pii=False,
        
        # 릴리즈 버전 (Git 커밋 해시로 자동 설정 가능)
        release=os.environ.get('SENTRY_RELEASE', 'ai-emotion-diary@1.0.0'),
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from django.core.exceptions import ImproperlyConfigured

def get_env_variable(var_name, default=None):
    """환경 변수를 가져오거나 예외를 발생시킵니다."""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Phase 1: Remove insecure fallback. Must be set in env.
SECRET_KEY = get_env_variable('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# 허용 호스트 (프로덕션에서는 환경 변수로 설정)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.postgres', # for pgvector HNSW index
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',  # OpenAPI 3.0 문서
    # Local apps
    'diary',
    # Monitoring
    'django_prometheus',
]

if IS_TESTING:
    # Disable migrations during tests to allow SQLite to handle pgvector models
    MIGRATION_MODULES = {
        'diary': None,
    }
    # Remove Postgres-specific apps for SQLite tests
    INSTALLED_APPS = [app for app in INSTALLED_APPS if app != 'django.contrib.postgres']
    
    # Force LocMemCache for tests to avoid Redis dependency
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware', # 모니터링 시작
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware', # 모니터링 종료
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Docker 환경에서 Postgres 사용
if os.environ.get('POSTGRES_DB'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', 5432),
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko'  # 기본 언어: 한국어

# 지원 언어 목록
LANGUAGES = [
    ('ko', '한국어'),
    ('en', 'English'),
]

# 번역 파일 경로
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# 스토리지 설정 (Cloudflare R2 / S3)
# =============================================================================
# 환경 변수에 R2/S3 정보가 있으면 클라우드 스토리지 사용
if os.environ.get('AWS_ACCESS_KEY_ID'):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.environ.get('AWS_ACCESS_KEY_ID'),
                "secret_key": os.environ.get('AWS_SECRET_ACCESS_KEY'),
                "bucket_name": os.environ.get('AWS_STORAGE_BUCKET_NAME'),
                "endpoint_url": os.environ.get('AWS_S3_ENDPOINT_URL'), # Cloudflare R2 Endpoint
                "custom_domain": os.environ.get('AWS_S3_CUSTOM_DOMAIN'), # Public Domain
                "region_name": "auto", # R2는 region 무관 (auto)
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # 미디어 URL을 R2 도메인으로 설정
    if os.environ.get('AWS_S3_CUSTOM_DOMAIN'):
        MEDIA_URL = f"https://{os.environ.get('AWS_S3_CUSTOM_DOMAIN')}/"
else:
    # 로컬 스토리지 (기본)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# OpenAI API Key
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Gemini API Key (For Free AI Chat)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

# Gemini Imagen Model (Optional)
GEMINI_IMAGE_MODEL = os.environ.get('GEMINI_IMAGE_MODEL', 'gemini-2.5-flash-image')

# Gemini Text Model (Emotion/Summary/Template)
GEMINI_TEXT_MODEL = os.environ.get('GEMINI_TEXT_MODEL', 'gemini-3-flash-preview')

# 일기 내용 암호화 키 (32바이트 Base64 인코딩)
# 프로덕션에서는 반드시 환경 변수로 설정할 것!
# 생성 방법: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
DIARY_ENCRYPTION_KEY = get_env_variable('DIARY_ENCRYPTION_KEY')

# [Phase 2] Key Rotation Support
# 키 버전 관리를 위한 Dictionary.
# 새로운 키를 추가할 때마다 버전을 올리고 여기에 추가합니다.
DIARY_ENCRYPTION_KEYS = {
    1: DIARY_ENCRYPTION_KEY,
    # 2: os.environ.get('DIARY_ENCRYPTION_KEY_V2'), # Future key
}


# 현재 활성화된(암호화 시 사용할) 키 버전
CURRENT_ENCRYPTION_VERSION = 1

# =============================================================================
# 이메일 설정 (비밀번호 재설정용)
# =============================================================================
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend'  # 개발: 콘솔 출력
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@emotionaldiary.com')

# =============================================================================
# 이메일 인증 정책 (환경별 분기)
# =============================================================================
# 개발 환경에서는 이메일 인증 없이도 회원가입 가능하도록 설정 가능
# 운영 환경에서는 반드시 True로 설정하여 보안 유지
EMAIL_VERIFICATION_REQUIRED = os.environ.get('EMAIL_VERIFICATION_REQUIRED', 'True').lower() in ('true', '1', 'yes')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'diary': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',  # 파일 업로드 지원
        'rest_framework.parsers.FormParser',
    ],
    # 페이지네이션 설정
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # 커스텀 예외 핸들러
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
    
    # ==========================================================================
    # Rate Limiting (속도 제한) 설정
    # 브루트포스 공격, DDoS, API 남용 방지
    # ==========================================================================
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # 기본 제한 (모든 엔드포인트에 적용)
        'anon': '100/hour',           # 비로그인 사용자: 시간당 100회
        'user': '1000/hour',          # 로그인 사용자: 시간당 1000회
        
        # 민감한 엔드포인트별 제한 (커스텀 Throttle 클래스에서 사용)
        'login': '5/min',             # 로그인: 분당 5회 (브루트포스 방지)
        'register': '5/hour',         # 회원가입: 시간당 5회 (스팸 계정 방지)
        'password_reset': '3/hour',   # 비밀번호 재설정: 시간당 3회 (이메일 폭탄 방지)
        'email_resend': '3/10min',    # 이메일 재전송: 10분당 3회
        'ai_image': '3/day',          # AI 이미지 생성: 일당 3회 (무료 유저 기준, 비용 관리)
        'transcription': '30/hour',   # 음성 인식: 시간당 30회 (비용 관리)
        
        # DDoS 기본 방어
        'burst': '10/second',         # 버스트 제한: 초당 10회
        'sustained': '10000/day',     # 지속적 사용: 일당 10000회
    },
}

# Simple JWT 설정
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS 설정 (Cross-Origin Resource Sharing)
# 프론트엔드에서 백엔드 API 호출을 허용하기 위한 설정

# 개발 환경에서는 모든 도메인 허용 (배포 시 False로 변경)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# 배포 환경에서 허용할 도메인 목록
CORS_ALLOWED_ORIGINS = [
    # 로컬 개발 환경
    "http://localhost:3000",      # React 웹 개발 서버
    "http://127.0.0.1:3000",
    "http://localhost:8000",      # Django 개발 서버
    "http://127.0.0.1:8000",
    "http://localhost:8081",      # Expo 웹 개발 서버 (NEW)
    "http://127.0.0.1:8081",
    "http://localhost:19006",     # Expo 웹 개발 서버 (Legacy)
    "http://127.0.0.1:19006",
    # 모바일 앱 (Expo)
   "exp://localhost:8081",
    # TODO: 배포 환경 도메인 추가
    # "https://your-production-domain.com",
]

# 허용할 HTTP 메서드
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 허용할 HTTP 헤더
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# 자격 증명(쿠키, Authorization 헤더 등) 허용
CORS_ALLOW_CREDENTIALS = True

# Preflight 요청 캐시 시간 (초)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24시간


# =============================================================================
# Django 캐시 설정
# =============================================================================
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# 개발 환경에서는 로컬 메모리 캐시 사용, 프로덕션에서는 Redis 사용
if DEBUG and not os.environ.get('USE_REDIS', ''):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'diary',  # 캐시 키 접두사
            'TIMEOUT': 3600,  # 기본 캐시 만료 시간 (1시간)
        }
    }

# 캐시 키 TTL 설정 (초 단위)
CACHE_TTL = {
    'report': 3600,      # 감정 리포트: 1시간
    'calendar': 1800,    # 캘린더: 30분
    'heatmap': 3600,     # 히트맵: 1시간
    'popular_tags': 600, # 인기 태그: 10분
}


# =============================================================================
# Celery 설정 (비동기 태스크 처리)
# =============================================================================
# Redis 브로커 URL
CELERY_BROKER_URL = REDIS_URL

# 결과 백엔드 (선택사항)
CELERY_RESULT_BACKEND = REDIS_URL

# 태스크 직렬화 방식
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 시간대 설정
CELERY_TIMEZONE = TIME_ZONE

# 태스크 결과 만료 시간 (1시간)
CELERY_RESULT_EXPIRES = 3600

# 태스크 실패 시 재시도 설정
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# 태스크별 라우팅 (선택사항)
CELERY_TASK_ROUTES = {
    'diary.tasks.send_email_async': {'queue': 'email'},
    'diary.tasks.generate_pdf_async': {'queue': 'pdf'},
}

# 동시 실행 워커 수 제한
CELERY_WORKER_CONCURRENCY = 4

# =============================================================================
# Celery Beat 스케줄 (주기적 작업)
# =============================================================================
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 1. 벡터 인덱스 재빌드 (새벽 2시 30분)
    # 검색 성능 유지를 위해 HNSW 인덱스 최적화
    'reindex-vectors-daily': {
        'task': 'diary.tasks.reindex_vectors',
        'schedule': crontab(hour=2, minute=30),
    },
    
    # 2. 고아 이미지 정리 (새벽 3시 00분)
    # 스토리지 비용 절감을 위해 쓰지 않는 이미지 삭제
    'cleanup-unused-images-daily': {
        'task': 'diary.tasks.cleanup_unused_images',
        'schedule': crontab(hour=3, minute=0),
    },
    
    # 3. 오래된 백업 파일 정리 (새벽 4시 00분)
    'cleanup-old-exports-daily': {
        'task': 'diary.tasks.cleanup_old_exports',
        'schedule': crontab(hour=4, minute=0),
        'args': (7,), # 7일 지난 파일 삭제
    },
}

# =============================================================================
# drf-spectacular 설정 (OpenAPI 3.0)
# =============================================================================
SPECTACULAR_SETTINGS = {
    'TITLE': '감성 일기 API',
    'DESCRIPTION': 'AI 감정 분석 및 그림 생성 일기 서비스 API 문서',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
}
