# Generated by Django 6.0.1 on 2026-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diarytemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='auto_emotion_analysis',
            field=models.BooleanField(default=True, verbose_name='자동 감정 분석'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='daily_reminder_time',
            field=models.TimeField(blank=True, null=True, verbose_name='일기 알림 시간'),
        ),
    ]
