# Generated by Django 6.0.1 on 2026-01-12 07:56

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_userpreference_auto_emotion_analysis_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='diary',
            name='reflection_answer',
            field=models.TextField(blank=True, null=True, verbose_name='회고 답변'),
        ),
        migrations.AddField(
            model_name='diary',
            name='reflection_question',
            field=models.TextField(blank=True, null=True, verbose_name='회고 질문'),
        ),
        migrations.AddField(
            model_name='diary',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice/', verbose_name='음성 파일'),
        ),
        migrations.CreateModel(
            name='DiaryEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='diary.diary')),
            ],
        ),
    ]
