# Generated by Django 6.0.1 on 2026-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_diary_reflection_answer_diary_reflection_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_transcribing',
            field=models.BooleanField(default=False, verbose_name='변환 중 여부'),
        ),
        migrations.AddField(
            model_name='diary',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='음성 변환 텍스트'),
        ),
    ]
