# Generated by Django 6.0.1 on 2026-01-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_diary_is_transcribing_diary_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='version',
            field=models.IntegerField(default=1, verbose_name='버전'),
        ),
    ]
