# Generated by Django 6.0.1 on 2026-01-13 02:58

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_diary_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('WEEKLY', '주간'), ('MONTHLY', '월간')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary_text', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '요약',
                'verbose_name_plural': '요약들',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'period_type', '-start_date'], name='diary_diary_user_id_0baa59_idx')],
                'unique_together': {('user', 'period_type', 'start_date')},
            },
        ),
    ]
