# Generated by Django 6.0.1 on 2026-01-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_diarysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='encryption_version',
            field=models.IntegerField(default=1, verbose_name='암호화 버전'),
        ),
    ]
