# Generated by Django 6.0.1 on 2026-01-13 06:18

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_diary_encryption_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diaryembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='diary_vector_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='diarysummary',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='summary_vector_idx', opclasses=['vector_l2_ops']),
        ),
    ]
