# Generated by Django 6.0.1 on 2026-01-13 08:18

import diary.models.chat_models
import diary.models.summary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_diaryembedding_diary_vector_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diaryembedding',
            name='diary_vector_idx',
        ),
        migrations.RemoveIndex(
            model_name='diarysummary',
            name='summary_vector_idx',
        ),
        migrations.AddField(
            model_name='diary',
            name='search_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='검색 키워드 (암호화 X)'),
        ),
        migrations.AlterField(
            model_name='diaryembedding',
            name='vector',
            field=diary.models.chat_models.VectorField(),
        ),
        migrations.AlterField(
            model_name='diarysummary',
            name='vector',
            field=diary.models.summary.VectorField(blank=True, null=True),
        ),
    ]
