# Generated by Django 6.0.1 on 2026-01-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_remove_diaryembedding_diary_vector_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='프리미엄 멤버십 여부'),
        ),
    ]
