# Generated by Django 6.0.1 on 2026-01-14 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_userpreference_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '스팸'), ('inappropriate', '부적절한 콘텐츠'), ('violence', '폭력적 콘텐츠'), ('hate_speech', '혐오 발언'), ('harassment', '괴롭힘'), ('false_info', '허위 정보'), ('other', '기타')], max_length=100, verbose_name='신고 사유')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고 시각')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('reviewing', '검토 중'), ('resolved', '해결됨'), ('dismissed', '기각됨')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토 시각')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='처리 내용')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='diary.diary', verbose_name='일기')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '콘텐츠 신고',
                'verbose_name_plural': '콘텐츠 신고 목록',
                'db_table': 'content_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='content_rep_created_1d1e0f_idx'), models.Index(fields=['status', '-created_at'], name='content_rep_status_fc1cfa_idx'), models.Index(fields=['diary'], name='content_rep_diary_i_3963cb_idx')],
                'unique_together': {('diary', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='FlaggedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('violence', '폭력'), ('hate_speech', '혐오 발언'), ('self_harm', '자해'), ('illegal', '불법 활동'), ('harassment', '괴롭힘'), ('sexual', '성적 콘텐츠')], max_length=50, verbose_name='감지 유형')),
                ('confidence', models.FloatField(help_text='AI 감지 신뢰도 (0.0 ~ 1.0)', verbose_name='신뢰도')),
                ('detected_keywords', models.JSONField(blank=True, default=list, verbose_name='감지된 키워드')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='감지 시각')),
                ('reviewed', models.BooleanField(default=False, verbose_name='검토 완료')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토 시각')),
                ('action_taken', models.CharField(choices=[('none', '조치 없음'), ('warning', '경고'), ('hidden', '숨김'), ('deleted', '삭제')], default='none', max_length=20, verbose_name='조치 내용')),
                ('admin_notes', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='diary.diary', verbose_name='일기')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '유해 콘텐츠 감지',
                'verbose_name_plural': '유해 콘텐츠 감지 목록',
                'db_table': 'flagged_content',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='flagged_con_detecte_8ed90e_idx'), models.Index(fields=['reviewed', '-detected_at'], name='flagged_con_reviewe_51e392_idx'), models.Index(fields=['flag_type'], name='flagged_con_flag_ty_15417b_idx')],
            },
        ),
    ]
