# Generated by Django 6.0.1 on 2026-01-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_contentreport_flaggedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='현재 연속 작성'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='emotion_trend_alert',
            field=models.BooleanField(default=True, verbose_name='감정 트렌드 알림'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_diary_date',
            field=models.DateField(blank=True, null=True, verbose_name='마지막 일기 작성일'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='max_streak',
            field=models.IntegerField(default=0, verbose_name='최고 연속 작성'),
        ),
    ]
