# Generated by Django 6.0.1 on 2026-01-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_userpreference_current_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryimage',
            options={'ordering': ['-created_at'], 'verbose_name': '일기 이미지', 'verbose_name_plural': '일기 이미지들'},
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='이미지 설명'),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='is_ai_generated',
            field=models.BooleanField(default=True, verbose_name='AI 생성 여부'),
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='uploaded_file',
            field=models.ImageField(blank=True, null=True, upload_to='diary_uploads/%Y/%m/', verbose_name='업로드 이미지'),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='새 대화', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI'), ('system', '시스템')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('referenced_diaries', models.ManyToManyField(blank=True, related_name='chat_references', to='diary.diary')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diary.chatsession')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
    ]
