# Generated by Django 6.0.1 on 2026-01-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_alter_diaryimage_options_diaryimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개 여부'),
        ),
        migrations.AddField(
            model_name='diary',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='공유 토큰'),
        ),
    ]
