# Generated by Django 6.0.1 on 2026-01-26 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_diary_is_public_diary_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('READ', '조회'), ('CREATE', '생성'), ('UPDATE', '수정'), ('DELETE', '삭제'), ('LOGIN', '로그인'), ('LOGOUT', '로그아웃'), ('FAILED_LOGIN', '로그인 실패'), ('ACCESS_DENIED', '접근 거부')], max_length=20)),
                ('resource', models.CharField(help_text='접근한 리소스 (예: Diary:123)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='SUCCESS', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='diary_audit_user_id_0a639d_idx'), models.Index(fields=['created_at'], name='diary_audit_created_a0a00f_idx')],
            },
        ),
    ]
